### ISSUE TITLE
Could not include config file  darwin.config

### ISSUE THREAD

**Issue by markmacau** [EricssonResearch/openwebrtc#354]
I got an error that "Configuration Error: Could not include config file (/MYPATH/cerbero/config/darwin.config)" when I run "./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc" and even bootstraping as  "./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap".

Can anybody suggest me what is wrong?

My OS is Mac OS X Yosemite 10.10.2 on MacBookPro with xcode Version 6.3.1.

Thanks,

Mark

**Comment by superdump** [comment]
When I've seen that issue it is because of a problem with the dist symbolic link. Did you do this bit: https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC#mac-os-x-host ? You can check from your cerbero clone:
```
ls -l dist
```

**Comment by markmacau** [comment]
Thanks. It works now. Somehow my symlink was pointed to /Library/Frameworks/OpenWebRTC.framework/Versions/0.1.  Maybe I got wrong instruction.

**Comment by superdump** [comment]
That changed yesterday as we are about to make a release.

**Comment by umar021** [comment]
Hej ..... I am still having this problem, although  I have checked from my cerebra clone and it is 
/Library/Frameworks/OpenWebRTC.framework/Versions/0.3

My OS is Mac OS X Yosemite 10.10.3 on MacBookPro with Version 10.10.3

Can anyone  guide me please. 

/Umar

**Comment by umar021** [comment]
I am getting this error 

./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap
WARNING: Using default configuration because /Users/emarnir/.cerbero/cerbero.cbc is missing
Traceback (most recent call last):
  File "./cerbero/utils/__init__.py", line 275, in parse_file
    execfile(filename, dict)
  File "/Users/emarnir/cerbero/config/darwin.config", line 88, in <module>
    raise Exception ("GL headers path not found: %s" % gl_headers)
Exception: GL headers path not found: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Headers
Configuration Error: Could not include config file (/Users/emarnir/cerbero/config/darwin.config)
