### ISSUE TITLE
ios / build for armv7s and arm64

### ISSUE THREAD

**Issue by iamyellow** [EricssonResearch/openwebrtc#48]
hey! thanks for this great effort!
is there any chance to compile for architectures > armv7 for iOS?

**Comment by mlakkadshaw** [comment]
is 64bit working now?

Thanks

**Comment by superdump** [comment]
I believe so. I am literally building everything from current cerbero as I write in order to test all the example apps. That will include testing apps using 64-bit on an iPhone 6 Plus. We have identified some bits and pieces that will still need further assembly optimisation specifically for ARM64 but there should be C fallback code if absolutely necessary but we're also working to avoid unnecessary software processing.

**Comment by stefanalund** [comment]
There are still problems for apps that want to use the JavaScript bridge, such as Bowser and other hybrid apps: https://github.com/EricssonResearch/openwebrtc/issues/177

**Comment by mlakkadshaw** [comment]
Thanks for the update, sadly my app is a hybrid app which uses javascript bridge, so it will not work in 64bit right?

**Comment by stefanalund** [comment]
Not yet but it will! We are working on it. Watch the other issue I linked to for progress. In the meantime you can develop using 32-bit only. Look at the sample apps if you're unsure of how the build settings should be set up.

**Comment by sdroege** [comment]
Most likely not, you can try though, maybe you're lucky and don't run into that specific problem. We're looking into that problem.

**Comment by mlakkadshaw** [comment]
Thanks.
Will try building using Cerebro, hopefully it will build. :)

**Comment by superdump** [comment]
There was a crash bug in JavaScriptCore on 64-bit that is fixed by updating libffi. However, updating libffi breaks the libffi build for 32-bit arm, at least for iOS.

**Comment by superdump** [comment]
libffi now works with JavaScriptCore on both 32-bit and 64-bit. Use cerbero and it works.
