### ISSUE TITLE
OpenWebRTC web demo and test-client app with H264 encoding

### ISSUE THREAD

**Issue by rrcarlosrodriguez** [EricssonResearch/openwebrtc#480]
Hi, I'm trying to probe the openwebrtc H264 encoding with the openwebrtc web demo and the test-client app, but I get this error when I use Google Chrome:

Failed to parse SessionDescription. Failed to parse video codecs correctly.

And when I use Firefox:

InvalidSessionDescriptionError: Failed to negotiate codec details for all codecs

Is there something wrong with the web app, it doesn't have H264 support yet or I'm missing something?

**Comment by rrcarlosrodriguez** [comment]
Hi
Thank you for your help, but it didn't fix the problem. I think my problem is the same as #425 , #466 and #443 .
I have being trying to add this line "a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=0;packetization-mode=1" to the offer SDP in the test-client app, specifically in the function send_answer(), like you suggested, but it didn't change anything and I am still having no video on the web demo.

**Comment by tanmayac** [comment]
Hi,

     I faced a similar issue, albeit with a modified version of test-client
app. I had also done a quick fix to add the parameters on the fmtp line.
The problem seems to happen with H264 and Firefox combination. In my case
libnice was not able to select a candidate. This was happening because in
test-client we tend to save the candidates only when an OwrMediaSession is
allocated. This happens only when we receive an offer.

     What was happening was that the correct candidates were being sent by
firefox before the offer was sent across. handle_remote_candidate ignores
the candidates if OwrMediaSession is not set. This resulted in the
candidate information not reaching libnice and well nothing worked.

     You could debug your situation by enabling libnice debug by setting
the following environment variables before starting test-client.

export G_MESSAGES_DEBUG=all
export NICE_DEBUG=all

     It would also make sense to verify if the fmtp line is getting
converted to the sdp by SDP.js. It was a while ago but when I was working
the sdp.js on the demo.openwebrtc.io was not the latest one.

Tanmaya

On Wed, Oct 14, 2015 at 4:13 AM, rrcarlosrodriguez <notifications@github.com

**Comment by rrcarlosrodriguez** [comment]
Hi, thanks for your help. You mentioned that you did a quick fix to add the parameters on the fmtp line. How did you do that? 
And how can I verify if the fmtp line is getting converted to the sdp?

**Comment by tanmayac** [comment]
Hi,

    I have attached the sdp.js for your quick reference and the the details
of fmtp line (added as json) in test_client are mentioned below.

Regards
Tanmaya

json_builder_set_member_name(builder, "parameters");
json_builder_begin_object(builder);

json_builder_set_member_name(builder, "profileLevelId");

json_builder_add_string_value(builder, "42c01e");

json_builder_set_member_name(builder, "levelAsymmetryAllowed");
json_builder_add_int_value(builder,val.lvl_as_all);

json_builder_set_member_name(builder, "packetizationMode");
json_builder_add_int_value(builder, val.p_mode);
json_builder_end_object(builder);


On Thu, Oct 22, 2015 at 9:02 PM, rrcarlosrodriguez <notifications@github.com

**Comment by AIMA2015** [comment]
Hi Tanmaya.

I know it has been a while, but would you mind sending me the changes you made in the sdp.js file?  I am starting to learn about webrtc and any help would be very appreciated.

Thanks a lot,

Ana
