### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [EricssonResearch/openwebrtc#611]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. **openwebrtc** was in my list. However, I observed that the software history of when the software was developed as a proprietary software was not kept after the transition to Github.

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask **openwebrtc** developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the _core developers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the _newcomers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by gustavopinto** [comment]
Hi @sdroege, do you have any comments?

**Comment by sdroege** [comment]
You will have to ask @superdump or @stefanalund, sorry :)

**Comment by superdump** [comment]
1. There were aspects that we could not release as Open Source and that needed to remain as being proprietary. It was considered safest to remove those parts, flatten the history and then publish.

2. I am not aware of any problems. Given question 3 it seems like you are defining core developers as those who worked on the project before its public release. So, history prior to public release was retained internally but I do not believe that we have ever had the need to look back at it. The core developers either knew the history or have not needed to look up anything.

3. For those who have worked on the code since it was published publicly, they have the code to look at and also code which is non-obvious should anyway have comments, else they could ask people who worked on the code before it was released. I cannot say that I am aware of any questions regarding code that required information from prior to the release.

4. As mentioned, I am not aware of it having had impact but I welcome comments from others about things that have been difficult to understand as a result of not having the code's evolution prior to the public release.

**Comment by gustavopinto** [comment]
Hi @superdump  and @sdroege, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
